### ISSUE TITLE
Lettering.js interferes with existing elements inside title

### ISSUE THREAD

**Issue by KuraFire** [davatron5000/Lettering.js#5]
All existing elements inside a title get removed, so when you have, for example, a fancy Baskerville-Italic ampersand inside a title, it gets killed by the script which ignores all elements inside it.

Example that breaks somewhat: `<h1>Photos <em>&amp;</em> Videos</h1>`

**Comment by flexelektro** [comment]
I dont understand why not use t[0].innerHTML instead of t.text() ...
This would preserve inner markup.

**Comment by quantrung9** [comment]
Look like the https://github.com/yuanqing/charming solved this problem.
