### ISSUE TITLE
The third individual twitter address is wrong~

### ISSUE THREAD

**Issue by Keystion** [davatron5000/Lettering.js#62]
“WHAT PEOPLE ARE SAYING” portion of the [URL](http://letteringjs.com/) preview,
The third individual twitter address is wrong.
It's right https://twitter.com/fchimero/.
![wrong_url](https://cloud.githubusercontent.com/assets/2408287/7018089/b69ccca8-dd32-11e4-9b1d-43e88fd041f9.png)

**Comment by davatron5000** [comment]
Hrm. I think that tweet just went away. I'll file this as a "BUMMER" but probably something we're not looking to fix.
