### ISSUE TITLE
Minified source?

### ISSUE THREAD

**Issue by lkraav** [davatron5000/Lettering.js#66]
Ciao guys. Was looking for the minified source.
1. https://github.com/davatron5000/Lettering.js/downloads has some pretty ancient stuff
2. shouldn't .min.js be part of the main repo for whatever one wants to do with `bower` and themsuch?

**Comment by davatron5000** [comment]
Probably need to update the downloads.

We removed the `.min.js` as it was resulting in a whole new commit every time we updated and most people use some kind of uglify/minify step in their build process. `bower` kinda influences my opinion, but I still feel like people should either minify themselves OR have a build step.

Thoughts?

**Comment by lkraav** [comment]
@davatron5000 well, a large majority of projects do the minified commit updates, either continously, or at least at release time - it's rare to not find a `.min.js` version after `npm install`. Could start with release time only updates, since it solves at least 80% of the problem with 20% or less effort. I doubt anybody will complain about not having the latest HEAD commit minified, that level of granularity could certainly be handled locally for those who need it.
