### ISSUE TITLE
Webpack usage

### ISSUE THREAD

**Issue by corbanb** [davatron5000/Lettering.js#71]
Do you all have any way to show how this is used with webpack? Be great to see this documented some place.

**Comment by sjelfull** [comment]
You first need the [imports-loader](https://github.com/webpack/imports-loader). You also need to pull in Lettering.js through something like npm. I've [added package.json to a fork](https://github.com/sjelfull-forks/Lettering.js).

Then do something like this:
```
require('imports?jQuery=jquery!letteringjs');
```

You should be able to use Lettering.js as normal.

**Comment by VaelVictus** [comment]
This was all it took for me. I happen to couple it with textillate. Both packages installed from npm.

```
import $ from 'jquery';  
window.jQuery = $; window.$ = $;

import 'letteringjs';
import textillate from 'textillate';
```

I also use this in my webpack config, in case you aren't already.

```
// expose jquery's $ for imports
  plugins: [
     new webpack.ProvidePlugin({
       $: 'jquery',
       jQuery: 'jquery'
     })
  ]
```
