### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by viniciuskol** [davatron5000/Lettering.js#75]
Fix for unicode support:
function injector(t, splitter, klass, after) {
        var text = t.text(),
            inject = '',
            i = 0;
        for (let char of text) { //this kind of iterator is unicode safe
            inject += '<span class="' + klass + (i + 1) + '" aria-hidden="true">' + char + '</span>' + after;
            i++;
        }
        t.attr('aria-label', text)
            .empty()
            .append(inject)
}
For more information: http://www.2ality.com/2015/01/es6-strings.html

**Comment by davatron5000** [comment]
Introducing `for (let char of text)` introduces a pretty intense ES6 dependency that I'm not sure we're ready to for. This is a pretty "legacy" plugin to say the least.
