### ISSUE TITLE
It's not working for me, wordpress

### ISSUE THREAD

**Issue by ckubs** [davatron5000/Lettering.js#76]
Properly called the script in my theme functions file, added this code to the header`<script type="text/javascript">
      $(document).ready(function() {
        $(".site-description").lettering();
      });
</script>`... site-description being the p class of my site tagline, and nothing is happening. :(
Thanks for any help.

**Comment by davatron5000** [comment]
When working with jQuery in WordPress you can't use the `$` shorthand. replace that with `jQuery` and it should work.

Read more: http://fixingthesejquery.com/#slide1

Closing. Not an issue with the plugin, an issue with the implementation.

**Comment by ckubs** [comment]
Working. Thank you :)
