### ISSUE TITLE
No dependency

### ISSUE THREAD

**Issue by incompletude** [davatron5000/Lettering.js#83]
Is there any plans to offer this amazing library without the jQuery dependency? :)

**Comment by davatron5000** [comment]
https://github.com/davatron5000/Lettering.js/wiki/More-Lettering.js

Here's a few options. I don't know if they support the `aria-label` accessibility features we added most recently.

Short answer: I probably won't maintain a version without jQuery, but it'd be easy or a good beginner challenge to write your own I think.
