### ISSUE TITLE
empty character disappear when display: inline-block

### ISSUE THREAD

**Issue by romain-granai** [davatron5000/Lettering.js#84]
Hi,

I'm trying to animate the span created by the plugin (using css transform), in order to do that I have to convert each span into display: inline-block, unfortunately, empty characters disappears, and there is no more space between words. I tried to target those characters in css using :empty but the span is not really empty (there is an empty space). Am I missing something? can't really find answer to that.

Is it possible to add a class to those empty span?

![image](https://user-images.githubusercontent.com/10668797/26887685-8f7f1ba6-4ba0-11e7-88c2-01ebd3b13e9b.png)

![image](https://user-images.githubusercontent.com/10668797/26887744-bba27f3e-4ba0-11e7-9e77-71ead415e753.png)

**Comment by romain-granai** [comment]
I've fixed that by modifying this part of the code : 

```
	function injector(t, splitter, klass, after) {
		var text = t.text()
		, a = text.split(splitter)
		, inject = '';
		if (a.length) {
			console.log(a);
			$(a).each(function(i, item) {
				if(item === " "){
					inject += '<span class="'+klass+(i+1)+' char-empty" aria-hidden="true">'+item+'</span>'+after;
				}else{
					inject += '<span class="'+klass+(i+1)+'" aria-hidden="true">'+item+'</span>'+after;
				}
			});
			t.attr('aria-label',text)
			.empty()
			.append(inject)

		}
	}
```
by adding the "char-empty" class if the item is empty, and keeping span.char-empty display: inline.

**Comment by davatron5000** [comment]
@romain-granai I think that's great! This is pretty specific to your design treatment, so I don't think we'll bake it into core. But this is meant to be modified to suit your needs. Good luck and I hope your site goes great.
