### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by lgund** [davatron5000/Lettering.js#85]
Hey,

are for the extension methods? I want to make something after he finished lettering, but I don´t find something on your documentation. I mean something like this:

`$("#myelement").lettering('words', function() {
   // Text
});`

**Comment by davatron5000** [comment]
We don't have any callback functionality but you could probably do some jQuery chaining...

```
$.fn.myFunc = function( el ) {
  console.log( el );
};
$("#myelement").lettering('words').myFunc();
```

Typically tho, after it runs, I just reselect the element.

```
$("#myelement").lettering('words');
function myFunc() {
  $("#myelement).doSomething();
}
```
