### ISSUE TITLE
lettering('lines') not working

### ISSUE THREAD

**Issue by ashehzadgec** [davatron5000/Lettering.js#92]
Hi,

I tried your lib for line splitting but it does not seem to be working at my end. Although characters and words work fine but lines don't. Below is the demo to reproduce.

https://codepen.io/ShehzadAsif/pen/wvezoNa?editors=1111

Regards,
Shehzad Asif

**Comment by davatron5000** [comment]
You need to a `<br/>` to the text get lines to work. More documentation here:

https://github.com/davatron5000/Lettering.js/wiki/Wrapping-lines-with-lettering%28%27lines%27%29

**Comment by ashehzadgec** [comment]
Hi,

Thanks for your reply, I have a confusion now that If I had to use <br> tag
to break in lines then it will not be adaptive to device width. For
example, I use 5 <br> tags for a paragraph on the desktop to break into
lines, and that same paragraph will require maybe 8 <br> tags for mobile
and then for tablet, and I'll have to do it manually again for other
devices and so on, kind of making it useless of use of .lines in this way
bcs I can do this with simply using span without removing this lib if I
have to break the lines manually. If I am missing something, I'll really
appreciate a demo for the same scenario.

**Comment by davatron5000** [comment]
Sorry, @ashehzadgec, it works how you described. I don't think Lettering will work for your situation. 

You may want to check out Big Text https://www.zachleat.com/web/bigtext-makes-text-big/
