### ISSUE TITLE
Words break into next line

### ISSUE THREAD

**Issue by shehzadasif** [davatron5000/Lettering.js#93]
Hi there,

I was trying your library, found out that I can't animate the text until I use display: inline-block for the chars. If I do that then words start to break as expected from "display:inline-block" property although what should happen is that when the word does not fit anymore within the available space it should move to next line ( kindly have a look at attached img and see what's happening with last word.  . Making it useless to use it. Is there any solution to that.
![lettering-issue](https://user-images.githubusercontent.com/96428705/147647842-da46d765-4428-461c-97a1-14ea1776ddaf.png)

**Comment by davatron5000** [comment]
Not being able to animate inline elements is a limitation of CSS not Lettering.js

See demo: https://codepen.io/davatron5000/pen/OJxQOPB

Sorry this didn't quite work as expected. You could try chaining `words` and `letters` to prevent the breaking https://github.com/davatron5000/Lettering.js/wiki/Chaining-with-lettering%28%29

**Comment by shehzadasif** [comment]
HI,

Thanks for the prompt reply, your solutions works out for me. But how I can
make it work out with next.js. I get the error that the "lettering is not
defined".

I really appreciate your help.
